"""Init

Revision ID: 96419783a9a1
Revises: 
Create Date: 2026-02-04 13:20:06.355716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96419783a9a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('who_create', sa.String(length=36), nullable=True),
    sa.Column('who_update', sa.String(length=36), nullable=True),
    sa.Column('when_create', sa.BigInteger(), nullable=False),
    sa.Column('when_update', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('who_create', sa.String(length=36), nullable=True),
    sa.Column('who_update', sa.String(length=36), nullable=True),
    sa.Column('when_create', sa.BigInteger(), nullable=False),
    sa.Column('when_update', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('who_create', sa.String(length=36), nullable=True),
    sa.Column('who_update', sa.String(length=36), nullable=True),
    sa.Column('when_create', sa.BigInteger(), nullable=False),
    sa.Column('when_update', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('who_create', sa.String(length=36), nullable=True),
    sa.Column('who_update', sa.String(length=36), nullable=True),
    sa.Column('when_create', sa.BigInteger(), nullable=False),
    sa.Column('when_update', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('read_permission', sa.Boolean(), nullable=True),
    sa.Column('read_all_permission', sa.Boolean(), nullable=True),
    sa.Column('create_permission', sa.Boolean(), nullable=True),
    sa.Column('update_permission', sa.Boolean(), nullable=True),
    sa.Column('update_all_permission', sa.Boolean(), nullable=True),
    sa.Column('delete_permission', sa.Boolean(), nullable=True),
    sa.Column('delete_all_permission', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('who_create', sa.String(length=36), nullable=True),
    sa.Column('who_update', sa.String(length=36), nullable=True),
    sa.Column('when_create', sa.BigInteger(), nullable=False),
    sa.Column('when_update', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'resource_id'),
    sa.UniqueConstraint('user_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
